config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'
  get 'show/:id'=>'static_pages#show', as: :show_picture
  get 'new'=>'static_pages#new', as: :new_picture
  post 'create'=>'static_pages#create', as: :pictures
  delete 'delete/:id'=>'static_pages#delete', as: :delete_picture

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :find_picture, except: [:index, :new, :create]

	def index
    @pictures = Picture.all
	end

	def show; end

	def new
    @picture = Picture.new
  end

  def create
    picture = Picture.create(picture_params)
    if picture
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  def delete
    @picture.destroy
    redirect_to root_path
  end

  private

  def find_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:name, :description, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railspics2</title>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header class="top-bar">
    <div class="row">
      <%= link_to image_tag('logo.svg',class: 'logo', alt: "Railspics logo"), root_path%>
      <%= link_to 'Agregar foto', new_picture_path, class:'button'%>
    </div>
  </header>

<%= yield %>

</body>
</html>

app/views/static_pages/index.html.erb
<div class="main-content">
    <div class="row post-index">
      <% @pictures.each do |picture| %>
        <div class="card post-index--box">
          <%= image_tag picture.image_url, class:'post-index--box__image', alt:"food picture" %>
          <div class="flex-row">
            <%= link_to 'Ver', show_picture_path(picture)%>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/static_pages/new.html.erb
<div class="main-content">

    <div class="row flex-center">
      <div class="flex-column card card--padding">
        <h1>Agregar foto</h1>
        <%= form_for @picture do |f| %>
          <div>
            <%= f.label :name, 'Título'%>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div>
            <%= f.label :description, 'Descripción'%>
            <%= f.text_area :description, rows:'8', cols:'40'%>
          </div>
          <div>
            <%= f.label :image_url, 'URL'%>
            <%= f.text_field :image_url %>
          </div>
          <div class="flex-row">
            <%= f.submit 'Agregar', class:'button action'%>
          </div>
        <% end %>
      </div>
    </div>

  </div>

app/views/static_pages/show.html.erb
<div class="main-content">

    <div class="row flex-center">
      <div class="flex-row card">
        <img class="post-show--image" src="http://lorempixel.com/500/500/food/7" alt="food picture" />
        <div class="post-show--box flex-column">
          <h1><%= @picture.name %></h1>
          <p>
            <%= @picture.description %>
          </p>
          <div class="flex-row">
            <%= link_to 'Agregar', new_picture_path, class:'button action'%>
            <%= link_to 'Eliminar', delete_picture_path(@picture), method: :delete ,class:'button alert'%>
          </div>
        </div>
      </div>
    </div>

  </div>